version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pasantic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis_server:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - ./cache:/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=pasantic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SECRET_KEY=django-insecure-p190@-veln(_-=b6cwpkobhx4ke*$r^sx!5-&3mhux2w!_m#nw
      - DEBUG=True
      - ALLOWED_HOST=*
    depends_on:
      - db
      - redis_server
