# Generated by Django 4.0.1 on 2022-01-17 03:09

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today, null=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=60)),
                ('type_of_workDay', models.CharField(max_length=15)),
                ('requirements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=5)),
                ('challenges', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=5)),
                ('profile', models.CharField(max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_months', models.IntegerField(max_length=2)),
                ('remuneration', models.DecimalField(decimal_places=3, max_digits=6)),
                ('have_remuneration', models.BooleanField(default=False)),
                ('owner_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='enterprise_of_%(class)s', to='organization.enterprise')),
            ],
            options={
                'verbose_name_plural': 'Internships',
            },
        ),
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today, null=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('state', models.BooleanField(default=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='internship_of_%(class)s', to='internships.internship')),
                ('postulant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_of_%(class)s', to='user.intern')),
            ],
            options={
                'verbose_name_plural': 'Postulations',
            },
        ),
    ]
