# Generated by Django 4.0.1 on 2022-02-08 01:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internship',
            options={},
        ),
        migrations.AlterModelOptions(
            name='postulation',
            options={},
        ),
        migrations.AlterField(
            model_name='internship',
            name='challenges',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=5),
        ),
        migrations.AlterField(
            model_name='internship',
            name='duration_months',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='internship',
            name='requirements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=5),
        ),
        migrations.AlterField(
            model_name='internship',
            name='type_of_workDay',
            field=models.CharField(choices=[('T', 'Teletrabajo'), ('P', 'Presencial'), ('H', 'Hibrido')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='postulation',
            name='state',
            field=models.CharField(choices=[('I', 'Iniciada'), ('P', 'Pendiente'), ('R', 'Rechazada'), ('A', 'Aprobada'), ('T', 'Terminada')], default='I', max_length=1),
        ),
    ]
