# Generated by Django 4.0.1 on 2022-01-16 22:16

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True, null=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('card_id', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(max_length=100)),
                ('cellphone', models.CharField(max_length=13)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_of_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.person')),
            ],
            options={
                'abstract': False,
            },
            bases=('user.person',),
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.person')),
                ('born_date', models.DateField()),
                ('address', models.CharField(max_length=30)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('institution', models.CharField(max_length=100)),
                ('study_field', models.CharField(max_length=100)),
                ('certifications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=5)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=3)),
                ('references', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=2), blank=True, null=True, size=5)),
            ],
            options={
                'abstract': False,
            },
            bases=('user.person',),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['card_id'], name='card index person'),
        ),
        migrations.AddField(
            model_name='intern',
            name='friends',
            field=models.ManyToManyField(blank=True, to='user.Intern'),
        ),
    ]
